# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt5_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

class Ui_Beechat_Networks(object):
    def setupUi(self, Beechat_Networks):
        Beechat_Networks.setObjectName("Beechat_Networks")
        Beechat_Networks.resize(730, 700)
        # setting font
        QtGui.QFontDatabase.addApplicationFont("Nunito.ttf")
        font = QtGui.QFont("Nunito", 14)
        
        # setting id font
        id_font = QtGui.QFont("Nunito", 12)
        
        Beechat_Networks.setFont(font)
        Beechat_Networks.setWindowOpacity(1.0)
        Beechat_Networks.setAutoFillBackground(False)
        Beechat_Networks.setStyleSheet("background-color:  #010523;")
        self.centralwidget = QtWidgets.QWidget(Beechat_Networks)
        self.centralwidget.setObjectName("centralwidget")
        
        # logo
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(40, 20, 120, 120))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        
        # public broadcast label
        self.public_broadcast = QtWidgets.QLabel(self.centralwidget)
        self.public_broadcast.setGeometry(QtCore.QRect(240, 30, 371, 61))
        # font = QtGui.QFont()
        # font.setPointSize(21)
        self.public_broadcast.setFont(font)
        self.public_broadcast.setStyleSheet("color: rgb(255, 255, 255);")
        self.public_broadcast.setObjectName("public_broadcast")

        
        # id label
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 90, 400, 51))
        self.label.setFont(font)
        self.label.setStyleSheet("color: #a6a6a6 ;")
        self.label.setObjectName("label")
        
        # horizontal line
        self.line_widget = QWidget(self.centralwidget)
        self.line_widget.setObjectName(u"centralwidget")
        self.line = QFrame(self.line_widget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(40, 60, 441, 16))
        self.line.setCursor(QCursor(Qt.PointingHandCursor))
        self.line.setStyleSheet(u"color: #a6a6a6;")
        self.line.setLineWidth(2)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)

# ********************************************************************************************
        # frame 1
        self.frame1 = QtWidgets.QFrame(self.centralwidget)
        self.frame1.setGeometry(QtCore.QRect(20, 230, 491, 90))
        self.frame1.setStyleSheet("background-color: #1f243f;\n"
                        "border-radius: 45px;")
        self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        
        # label 2 (into frame 1)
        self.label_2 = QtWidgets.QLabel(self.frame1)
        self.label_2.setGeometry(QtCore.QRect(40, 0, 271, 41))
        
        self.label_2.setFont(id_font)
        self.label_2.setStyleSheet("color: #a6a6a6;")
        self.label_2.setObjectName("label_2")
        
        # label 3 (into frame1)
        self.label_3 = QtWidgets.QLabel(self.frame1)
        self.label_3.setGeometry(QtCore.QRect(40, 40, 281, 41))
        # font = QtGui.QFont()
        # font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        
# **********************************************************************************************
        # frame 2 starts here
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 340, 491, 120))
        self.frame_2.setStyleSheet("background-color: #1f243f;\n"
                "border-radius: 20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        
        # message id label
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(20, 0, 271, 41))
        # font = QtGui.QFont()
        # font.setPointSize(14)
        self.label_4.setFont(id_font)
        self.label_4.setStyleSheet("color: #a6a6a6;")
        self.label_4.setObjectName("label_4")
        
        # message
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 451, 68))
        # font = QtGui.QFont()
        # font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")

# *******************************************************************************
     
        # reply message frame
        self.reply = QtWidgets.QFrame(self.centralwidget)
        self.reply.setGeometry(QtCore.QRect(340, 475, 371, 60))
        self.reply.setStyleSheet("background-color: #4857a8;\n"
                "border-radius: 30px;")
        self.reply.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.reply.setFrameShadow(QtWidgets.QFrame.Raised)
        self.reply.setObjectName("reply")
        
        # reply label inside reply_frame
        self.label_7 = QtWidgets.QLabel(self.reply)
        self.label_7.setGeometry(QtCore.QRect(30, 10, 281, 41))
        # font = QtGui.QFont()
        # font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        
        # input widget
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 550, 681, 101))
        self.widget.setObjectName("widget")
        
        # plain text edit inside qwidget
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget)
        # font = QtGui.QFont()
        # font.setPointSize(14)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 0, 640, 90))
        self.plainTextEdit.setStyleSheet("background-color: rgb(58, 60, 66);\n"
                "color: rgb(255, 255, 255);\n"
                "border-radius: 45px;\n"
                "padding: 20px;")
        self.plainTextEdit.setObjectName("plainTextEdit")
        
        # send button inside qwidget
        self.send_button = QtWidgets.QPushButton(self.widget)
        self.send_button.setGeometry(QtCore.QRect(590, 0, 90, 90))
        # font = QtGui.QFont()
        # font.setPointSize(14)
        self.send_button.setFont(font)
        self.send_button.setStyleSheet("color: rgb(255, 255, 255);\n"
                "border-radius: 45px;\n"
                "border: 2px solid white;")
        self.send_button.setObjectName("send_button")
        
        
        Beechat_Networks.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Beechat_Networks)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 730, 22))
        self.menubar.setObjectName("menubar")
        Beechat_Networks.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Beechat_Networks)
        self.statusbar.setObjectName("statusbar")
        Beechat_Networks.setStatusBar(self.statusbar)

        self.retranslateUi(Beechat_Networks)
        QtCore.QMetaObject.connectSlotsByName(Beechat_Networks)

    def retranslateUi(self, Beechat_Networks):
        _translate = QtCore.QCoreApplication.translate
        Beechat_Networks.setWindowTitle(_translate("Beechat_Networks", "Beechat Networks"))
        self.public_broadcast.setText(_translate("Beechat_Networks", "Public broadcast"))
        self.label.setText(_translate("Beechat_Networks", "My ID: 0013A20041EFADC2"))
        self.label_2.setText(_translate("Beechat_Networks", "0013A20041EFADC2"))
        self.label_3.setText(_translate("Beechat_Networks", "Hello Everyone"))
        self.label_4.setText(_translate("Beechat_Networks", "0013A20041EFADC2"))
        self.label_5.setText(_translate("Beechat_Networks", "Hello Everyone this is a message that is 73 characters long."))
        self.label_7.setText(_translate("Beechat_Networks", "Hello Everyone"))
        self.send_button.setText(_translate("Beechat_Networks", "send"))
        self.send_button.clicked.connect(self.prname)
    def prname(self):
        #     print("send button clicked")
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Beechat_Networks = QtWidgets.QMainWindow()
    ui = Ui_Beechat_Networks()
    ui.setupUi(Beechat_Networks)
    Beechat_Networks.show()
    sys.exit(app.exec_())
